#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

START=60

SERVICE_PID_FILE=/var/run/dbus.pid

start() {
	mkdir -m 0755 -p /var/lib/dbus
	mkdir -m 0755 -p /var/run/dbus
	[ -x /rom/mnt/cust/usr/bin/dbus-uuidgen ] && /rom/mnt/cust/usr/bin/dbus-uuidgen --ensure
	/rom/mnt/cust/usr/sbin/dbus-daemon --config-file=/rom/mnt/cust/etc/dbus-1/system.conf
}

stop() {
	/rom/mnt/cust/usr/sbin/dbus-daemon && rm $SERVICE_PID_FILE
}
